org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.java.home=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.parallel=false
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
